version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    depends_on:
      - db 
  db:
   image: postgres:latest
   environment:
   - POSTGRES_USER=gilad
   - POSTGRES_PASSWORD=gilad
   - POSTGRES_DB=mydatabase